Button component
devhausleipzig/camp-8-midterm-group-2 pull request #16
Opened 2023-01-09 13:40 UTC by amyria3

default / disabled state for primary / regular size
react component
basic story

2023-01-09 14:53 UTC, amyria3 commented
pls take a look

2023-01-09 15:44 UTC, dnmct requested changes

2023-01-09 15:44 UTC, dnmct commented on src/components/Button.tsx
> +        ${(primary)?'bg-yellow text-dark-light':'bg-dark-light text-white'}
use clsx for dynamically applying classes

2023-01-09 15:44 UTC, dnmct commented on src/components/Button.tsx
> +        ${(default_height)? 'h-[49px]':'h-[38px]'}`
dont use fixed heights...
button size is determined by the padding

2023-01-09 15:44 UTC, dnmct commented on src/stories/Button.stories.tsx
> +import { ComponentStory, ComponentMeta } from "@storybook/react";
those imports are deperecated use the storybook 7 syntax
https://storybook.js.org/docs/7.0/react/get-started/whats-a-story

2023-01-09 15:46 UTC, amyria3 commented on src/components/Button.tsx
> +        ${(default_height)? 'h-[49px]':'h-[38px]'}`
but then the whole design make brake once you add a larger font size :)

2023-01-10 09:04 UTC, NoHara42 commented on src/stories/Button.stories.tsx
> +// export const Primary = Template.bind({}) //what does .bind do
Normally it'd be expected to remove large blocks of old template, but for the codecamp this is fine.

2023-01-10 09:25 UTC, amyria3 commented
All done :)

2023-01-11 09:27 UTC, NoHara42 commented on src/components/Button.tsx
> +import "../index.css";
index.css should be imported in your main.tsx, or app.tsx file... something higher up in the app hierarchy. 

then remove this here.

2023-01-11 09:28 UTC, NoHara42 requested changes
one change left before merge

2023-01-11 13:14 UTC, amyria3 commented
all done!

2023-01-11 13:57 UTC, NoHara42 commented
remember to reverse merge before claiming that you're done @amyria3 ;)

2023-01-11 13:58 UTC, NoHara42 approved these changes

2023-01-11 13:59 UTC, merged