SearchInput
devhausleipzig/camp-8-midterm-group-2 pull request #17
Opened 2023-01-09 13:43 UTC by ThoJah

2023-01-10 13:53 UTC, ThoJah commented
SearchInput Issue complete and ready for review

2023-01-11 09:41 UTC, NoHara42 commented on src/components/SearchInput.tsx
> +import "../index.css";
remove this and place the import higher up in the hierarchy for your project. i.e. in main.tsx or app.tsx

2023-01-11 09:42 UTC, NoHara42 commented on src/stories/SearchInput.stories.tsx
> +// export const Primary = Template.bind({});
please remove large blocks of unused code before committing

2023-01-11 09:44 UTC, NoHara42 commented on src/stories/SearchInput.stories.tsx
> +  const [value, setValue] = useState("Secondary");
why are you using reacts useState inside a story?

2023-01-11 09:45 UTC, NoHara42 requested changes
See comments, let's chat about this

2023-01-11 14:01 UTC, NoHara42 approved these changes
LGTM

2023-01-11 14:02 UTC, merged