Detail header layout
devhausleipzig/camp-8-midterm-group-2 pull request #34
Opened 2023-01-12 11:23 UTC by acz1992

2023-01-12 11:33 UTC, acz1992 commented
ready for review.

2023-01-13 14:30 UTC, NoHara42 commented on src/components/DetailHeaderLayOut.tsx
> +      <div></div>
empty div?

2023-01-13 14:31 UTC, NoHara42 commented on src/layouts/MoviesLayout.tsx
> +      <p>Movie layout</p>
this seems a bit literal?

2023-01-13 14:41 UTC, NoHara42 commented on src/layouts/RootLayout.tsx
> +    path: "/movieid/details",
wouldn't "/:movieid/details" fit the example in the documentation?

https://reactrouter.com/en/main/routers/create-browser-router

2023-01-13 14:45 UTC, NoHara42 commented on src/routes/CastCrew.tsx
> +    toAddress: "../movie/details",
don't you need the `movieId` to be interpolated into this string in place of movie?

Think about using `useParams()` to get this id
https://reactrouter.com/en/main/hooks/use-params

2023-01-13 14:47 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +    toAddress: "../",
have you tested that this works?

2023-01-13 14:53 UTC, NoHara42 commented on src/routes/SelectTime.tsx
> +    toAddress: "../..",
does this go back to the homepage? shouldn't it go back to the movie details page?

2023-01-13 14:54 UTC, NoHara42 requested changes
just a few changes left @acz1992 
and remember to reverse merge when you're finished

2023-01-16 08:46 UTC, acz1992 commented on src/layouts/MoviesLayout.tsx
> +      <p>Movie layout</p>
This was just for sign posting for now, Maria is working on the Movies Layout page, so she will change this

2023-01-16 10:38 UTC, ThoJah commented
Instead of reusing the DetailHeader() with fixed URL's passed in as a argument, we use it only once now in MovieLayout() with an onClick={ ( ) => navigate(-1) }
When trying navigate(-1) before we also implemented the component on every page, which led to endless cycles.
Having it rendered only once solved that problem

Ready for Review

2023-01-16 11:30 UTC, ThoJah commented on src/components/DetailHeaderLayOut.tsx
> +      <div></div>
We use this div to distribute the space in the header equally, added a width now that matches the width of the backChevron

2023-01-18 13:49 UTC, dnmct approved these changes

2023-01-18 13:52 UTC, merged