Homepage View
devhausleipzig/camp-8-midterm-group-2 pull request #35
Opened 2023-01-12 15:20 UTC by iameru

this is a PR for #20 

there were some changes and refactoring necessary on other already merged components.

2023-01-13 15:00 UTC, NoHara42 commented on src/components/MovieCarussel.tsx
> +  console.log(movies[0]);
Should this belong on the main branch?

2023-01-13 15:03 UTC, NoHara42 commented on src/components/MovieCarussel.tsx
> +          <Link to={movie.id.toString()}>
For a more universal solution get into the habit of casting like: `String(movie.id)`
.toString() will return you a string representation of any object, which might not always be what you expect from a normal type conversion

2023-01-13 15:08 UTC, NoHara42 commented on src/utils/movies.ts
> +const SECRETKEY = "039ceb136bde381a9652fedddb79e1f1"
Changing this is not necessary for this review, but in future lessons we will learn why hard coding our secret keys isn't very secure.

2023-01-13 15:09 UTC, NoHara42 requested changes
just a couple small changes then good to go @iameru

2023-01-14 12:38 UTC, iameru commented on src/utils/movies.ts
> +const SECRETKEY = "039ceb136bde381a9652fedddb79e1f1"
thanks. I was looking into how to read from ENV in react as to at least keep the repo clean of the secrets. however react, as it is clientsided, will have the key necessary for each client anyway. still pushing the changes to read from Envs. some folk on stackoverflow wrote that its best practice to use our own API for these usecases as there it can be kept secret.

2023-01-14 12:51 UTC, iameru commented on src/components/MovieCarussel.tsx
> +  console.log(movies[0]);
fixed in 99be30b

2023-01-14 12:51 UTC, iameru commented on src/components/MovieCarussel.tsx
> +          <Link to={movie.id.toString()}>
fixed in 99be30b

2023-01-16 13:46 UTC, merged