Button Logics repaired / improved
devhausleipzig/camp-8-midterm-group-2 pull request #43
Opened 2023-01-13 10:41 UTC by amyria3

2023-01-13 15:43 UTC, NoHara42 commented
@amyria3 what issues does this relate to?

2023-01-16 08:37 UTC, NoHara42 commented on src/components/Button.tsx
> +  disabled?: true; //state
are you sure this is supposed to be `true`? What's the use of hard coding values of a prop here?

2023-01-16 08:38 UTC, NoHara42 requested changes
take a look at my comment

2023-01-16 12:25 UTC, amyria3 commented
Maybe there is no additional value... I just was so so happy that I understood how dan writes it 🥇 
and maybe its too late to change it now, to many people would be affected

2023-01-18 13:57 UTC, dnmct requested changes

2023-01-18 13:57 UTC, dnmct commented on src/components/Button.tsx
> +  disabled?: true; //state
this defo needs to be boolean and not true, the logic may work but its kind of a bad practice

better solution:
```
disabled?: boolean

function Button({
  type, 
  height, 
  label, 
  disabled = false
}:
ButtonProps){
```

this makes the prop optional to pass in and when you not pass it it's not disabled

2023-01-18 14:19 UTC, amyria3 commented
Yes, I made a patch for it once I understood the syntax you use and its beauty :) 
https://github.com/devhausleipzig/camp-8-midterm-group-2/blob/amyria3-patch-1/src/components/Button.tsx

2023-01-19 15:50 UTC, merged