MovieDetailsPage
devhausleipzig/camp-8-midterm-group-2 pull request #45
Opened 2023-01-13 10:47 UTC by amyria3

pls review :)

2023-01-16 08:53 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +  const movie_name: string = currentData.details.title;
try using destructuring to create these bindings!
(optional)

2023-01-16 08:53 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +  console.log("LINE /! " + posterUrl + currentData.details.poster_path);
we don't commit console.log to our main branches

2023-01-16 08:57 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +      className="bg-dark min-h-[667px] pb-[24px] py-[18px]"
Please see if you can find an alternative for these square bracket noted utility classes, ideally use pb-6, etc... if 667px is a breakpoint that is used often, set a value for it in the tailwind config

2023-01-16 08:57 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +      <div id="content_wrapper" className="h-[568px] absolute top-[75px] mx-[18px]">
see above

2023-01-16 08:57 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +          className="mt-0 w-[100%] max-h-[211px] overflow-hidden rounded-lg"
w-100% is the same as w-full, see above

2023-01-16 08:59 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +                  <span className="text-[rgba(34, 197, 94, 1)]">
see above

2023-01-16 09:00 UTC, NoHara42 commented on src/routes/MovieDetails.tsx
> +                <div id="director" className="">
empty className here

2023-01-16 09:01 UTC, NoHara42 commented on src/routes/oldCode.ts
> +// export type props = {
we shouldn't commit unused files that serve no purpose to main

2023-01-16 09:02 UTC, NoHara42 requested changes
Some changes to be made, but looks good!

2023-01-16 12:29 UTC, amyria3 commented on src/routes/oldCode.ts
> +// export type props = {
done

2023-01-16 12:33 UTC, amyria3 commented on src/routes/MovieDetails.tsx
> +          className="mt-0 w-[100%] max-h-[211px] overflow-hidden rounded-lg"
done

2023-01-16 12:36 UTC, amyria3 commented on src/routes/MovieDetails.tsx
> +      className="bg-dark min-h-[667px] pb-[24px] py-[18px]"
667 is the height that dan have chosen for the prototype. 

I can put this and bg-color into home component in branch main OR i can define it for #root in tailwind theme. What should I do?

2023-01-16 12:37 UTC, amyria3 commented on src/routes/MovieDetails.tsx
> +  console.log("LINE /! " + posterUrl + currentData.details.poster_path);
done

2023-01-16 12:38 UTC, amyria3 commented on src/routes/MovieDetails.tsx
> +  const movie_name: string = currentData.details.title;
would love to but have no clue how :)

2023-01-18 09:34 UTC, amyria3 commented on src/routes/MovieDetails.tsx
> +                  <span className="text-[rgba(34, 197, 94, 1)]">
done

2023-01-18 14:01 UTC, dnmct requested changes

2023-01-18 14:01 UTC, dnmct commented on src/routes/MovieDetails.tsx
> +      <div id="content_wrapper" className="h-[568px] absolute top-[75px] mx-[18px]">
height should almost always be determined by the content + padding 
Ned is right

2023-01-18 15:36 UTC, amyria3 commented
page_wrapper has a height since height for all full-page components is not implemented yet :)

2023-01-19 13:42 UTC, amyria3 commented
I would like to link my commit d1d4ec3 to this branch, is this possible?

2023-01-19 13:46 UTC, amyria3 commented
ALL DONE juhuuu

2023-01-19 14:06 UTC, franzwollang reviewed
In general, looks good.

2023-01-19 14:06 UTC, franzwollang commented on src/routes/MovieDetails.tsx
> +    console.log("TEST" + JSON.stringify(people));
Please remove console.log's before requesting a review

2023-01-19 14:06 UTC, franzwollang commented on src/routes/MovieDetails.tsx
> +//http://localhost:5173/315162 EXAMPLE URL TO TEST
please remove miscellaneous comments from code before requesting a review

2023-01-19 14:51 UTC, amyria3 commented on src/routes/MovieDetails.tsx
> +//http://localhost:5173/315162 EXAMPLE URL TO TEST
done

2023-01-19 15:23 UTC, merged