deleted vite.svg
devhausleipzig/camp-8-midterm-group-2 pull request #9
Opened 2023-01-06 10:07 UTC by ThoJah

Starting point

2023-01-06 15:22 UTC, NoHara42 commented on src/main.tsx
> +    path: "selecttime",
Create a parent route for the 3 screens (select-time, select-seat and the booking confirmation) called 'booking' and have 3 subroutes 'booking/time', 'booking/seats', 'booking/ticket', use a `<BookingLayout/>` parent Component that manages the state for all the child Elements.

2023-01-06 15:34 UTC, NoHara42 requested changes
Looks good, only a small addition needs to be made 👌

2023-01-09 10:21 UTC, dnmct requested changes

2023-01-09 10:21 UTC, dnmct commented on src/main.tsx
> +
With your current setup, you show the navbar on different pages. instead of using it in a layout.
Your should have 3 top level routes
- Login
- NavigationLayout
- MovieLayout (all the pages from movie-details to booking)

2023-01-09 10:47 UTC, Sebi900 commented
so i changed the the navbar into an layout and called it NavBarLayout.tsx. For the Login page we can use the RootLayout.tsx but if its better to have a LoginLayout.tsx i can do it as well.

2023-01-09 11:17 UTC, Sebi900 commented on src/main.tsx
> +
The latest push "3 top levels" has any needed changes within. This should be ready to review again pls.

2023-01-09 13:23 UTC, dnmct approved these changes

2023-01-09 13:24 UTC, merged

2023-01-16 15:19 UTC, iameru commented
changed selecttime route to be truly index in 3261a2d